name: Build and Deploy Artifact

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_NAME: webapp_v1
      CODE_DEPLOY_APPLICATION_NAME: csye6225-webapp
      CODEDEPLOY_APPLICATION_DEPLOYMENT_GROUP_NAME: csye6225-webapp-deployment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node 
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.0
      - run: 
         npm install
      
      - name: Archive Releases
        run: |
          mkdir codedeploy_artifact
          zip -r serverless_artifact .
          mv serverless_artifact.zip codedeploy_artifact

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload artifact to s3
        run: aws s3 sync ./codedeploy_artifact s3://${{secrets.S3_BUCKET_NAME}}

      - name: Update Lambda Function
        run: aws lambda update-function-code --function-name lambda_function_name --s3-bucket ${{ secrets.S3_BUCKET_NAME }} --s3-key serverless_artifact.zip --region us-east-1 > lambdaFile.txt

        